'use client'

import Navbar from '../components/navigation/Navbar'
import Footer from '../components/sections/Footer'
import ParallaxHero from '../components/effects/ParallaxHero'
import EventContactForm, { getFormFields } from '../components/forms/EventContactForm'
import { Car, DollarSign, Shield, Clock, TrendingUp, CheckCircle, Calculator, Users, ChevronDown, FileText, Search, HandshakeIcon, Zap } from 'lucide-react'
import { useState, useRef } from 'react'

interface FAQAccordionProps {
  id: string
  question: string
  answer: string
  isOpen: boolean
  onToggle: (id: string) => void
  faqRef: (el: HTMLDivElement | null) => void
}

function FAQAccordion({ id, question, answer, isOpen, onToggle, faqRef }: FAQAccordionProps) {
  return (
    <div 
      ref={faqRef}
      className="bg-dark-metal/50 border border-gray-600/30 rounded-lg overflow-hidden transition-all duration-500 hover:border-neon-blue/50"
    >
      <button
        onClick={() => onToggle(id)}
        className={`w-full px-8 py-6 text-left flex items-center justify-between transition-all duration-300 hover:bg-dark-metal/70 group ${
          isOpen ? 'bg-dark-metal/70' : ''
        }`}
      >
        <h3 className={`text-lg font-tech font-semibold transition-colors duration-300 ${
          isOpen ? 'text-neon-blue' : 'text-white group-hover:text-neon-blue'
        }`}>
          {question}
        </h3>
        <ChevronDown 
          className={`w-5 h-5 text-neon-blue transition-transform duration-300 ${
            isOpen ? 'rotate-180' : ''
          }`}
        />
      </button>
      
      <div 
        className={`overflow-hidden transition-all duration-500 ease-in-out ${
          isOpen ? 'max-h-96 opacity-100' : 'max-h-0 opacity-0'
        }`}
      >
        <div className="px-8 pb-6 pt-2">
          <div className="h-px bg-gradient-to-r from-transparent via-neon-blue/30 to-transparent mb-4" />
          <p className="text-gray-300 leading-relaxed">
            {answer}
          </p>
        </div>
      </div>
    </div>
  )
}

export default function VehiclePartnership() {
  const [openFAQ, setOpenFAQ] = useState<string | null>(null)
  const faqRefs = useRef<{ [key: string]: HTMLDivElement | null }>({})
  const [calculatorValues, setCalculatorValues] = useState({
    vehicleValue: 60000,
    dailyRate: 200,
    monthlyDays: 15
  })

  // Function to calculate appropriate daily rate based on vehicle value
  const calculateDailyRate = (vehicleValue: number) => {
    // Market-based pricing tiers
    if (vehicleValue >= 400000) return Math.round((vehicleValue * 0.005) / 50) * 50 // Ultra-luxury: ~0.5% of value per day
    if (vehicleValue >= 250000) return Math.round((vehicleValue * 0.004) / 50) * 50 // Super-luxury: ~0.4% of value per day
    if (vehicleValue >= 150000) return Math.round((vehicleValue * 0.0035) / 50) * 50 // High-end luxury: ~0.35% of value per day
    if (vehicleValue >= 60000) return Math.max(Math.round((vehicleValue * 0.003) / 50) * 50, 200) // Entry luxury: ~0.3% of value per day, minimum $200
    return 200 // Minimum daily rate
  }

  const faqs = [
    {
      id: 'vehicle-requirements',
      question: 'What vehicles qualify for the partnership program?',
      answer: 'We accept luxury and exotic vehicles valued at $60,000+, typically 7 years old or newer. This includes brands like Ferrari, Lamborghini, McLaren, Porsche, Audi R8, BMW i8, Mercedes AMG, and other high-end sports cars. Vehicles must be well-maintained with clean titles and current registration.'
    },
    {
      id: 'insurance-coverage',
      question: 'How does insurance work for my vehicle?',
      answer: 'Investors maintain their current personal insurance on their vehicle. When your vehicle is rented, renters must provide their own full coverage insurance throughout the entire rental period. We conduct thorough verification with the client\'s insurance company to ensure proper coverage. There is no liability on DT Exotics or the investor during rental periods.'
    },
    {
      id: 'vehicle-safety',
      question: 'How do you ensure my vehicle is treated properly?',
      answer: 'We thoroughly screen all clients, require security deposits, conduct pre and post-rental inspections, and only work with experienced luxury car renters. Our professional staff handles all vehicle interactions, and we maintain strict standards for vehicle care and presentation.'
    },
    {
      id: 'revenue-sharing',
      question: 'How does the 50/50 revenue split work?',
      answer: 'You receive 50% of all rental revenue generated by your vehicle. Payments are made monthly via direct deposit. We handle all booking, marketing, insurance, and customer service while you earn passive income from your vehicle investment.'
    },
    {
      id: 'vehicle-storage',
      question: 'Where is my vehicle stored when not rented?',
      answer: 'Vehicles are stored in our secure, climate-controlled facility with 24/7 monitoring and restricted access. This protects your investment from weather, theft, and unauthorized use while ensuring vehicles remain in pristine condition.'
    },
    {
      id: 'maintenance-responsibility',
      question: 'Who handles maintenance and repairs?',
      answer: 'Maintenance responsibilities are discussed during contract negotiations and may vary by investor. Typically, investors continue to handle and schedule all maintenance for their vehicles. However, we can offer access to our network of repair shops and services, which can save you money by avoiding dealership pricing for routine maintenance. We can also arrange to take over maintenance responsibilities if preferred.'
    }
  ]

  const toggleFAQ = (faqId: string) => {
    const newOpenFAQ = openFAQ === faqId ? null : faqId
    setOpenFAQ(newOpenFAQ)
    
    // Auto-scroll to the opened FAQ
    if (newOpenFAQ && faqRefs.current[newOpenFAQ]) {
      setTimeout(() => {
        faqRefs.current[newOpenFAQ]?.scrollIntoView({
          behavior: 'smooth',
          block: 'center'
        })
      }, 100)
    }
  }

  const monthlyRevenue = calculatorValues.dailyRate * calculatorValues.monthlyDays
  const yourShare = monthlyRevenue * 0.5
  const annualRevenue = yourShare * 12

  const benefits = [
    {
      icon: DollarSign,
      title: "Higher Revenue",
      description: "Earn 50% of premium daily rates ($500-2000+) vs Turo's lower rates and fees."
    },
    {
      icon: Shield,
      title: "Full Protection",
      description: "Comprehensive commercial insurance with no gaps or exclusions."
    },
    {
      icon: Users,
      title: "Professional Management",
      description: "Expert screening, marketing, and customer service handled for you."
    },
    {
      icon: TrendingUp,
      title: "Passive Income",
      description: "Generate consistent returns without any involvement or effort required."
    }
  ]

  const steps = [
    {
      icon: FileText,
      number: "01",
      title: "Submit Your Vehicle",
      description: "Complete our simple application with your vehicle details and photos."
    },
    {
      icon: Search, 
      number: "02",
      title: "Vehicle Evaluation",
      description: "Our team conducts a thorough inspection and market analysis."
    },
    {
      icon: HandshakeIcon,
      number: "03",
      title: "Partnership Agreement",
      description: "Review and sign our transparent partnership contract."
    },
    {
      icon: Zap,
      number: "04",
      title: "Start Earning",
      description: "Your vehicle joins our fleet and begins generating revenue immediately."
    }
  ]

  return (
    <main className="relative min-h-screen">
      <Navbar />
      {/* Hero Section */}
      <ParallaxHero
        imageSrc="/images/hero/Partners Hero.avif"
        alt="Partnership opportunities with DT Exotics"
      >
        <div className="relative z-20 flex h-full items-center justify-center px-4 pb-20">
          <div className="text-center max-w-5xl mx-auto">
            <h1 className="text-4xl md:text-6xl lg:text-7xl xl:text-8xl font-tech font-black mb-6">
              <span className="text-white">TURN YOUR</span><br />
              <span className="neon-text">GARAGE QUEEN</span><br />
              <span className="text-white">INTO A</span><br />
              <span className="neon-text-magenta">REVENUE KING</span>
            </h1>
            
            <p className="text-base sm:text-lg md:text-xl lg:text-2xl text-white mb-8 sm:mb-12 font-light max-w-4xl mx-auto leading-relaxed">
              Partner with Las Vegas's premier luxury rental service. Earn 50% of rental revenue while we handle everything else.
            </p>

            <div className="flex flex-col sm:flex-row gap-4 justify-center">
              <a href="#calculator" className="btn-primary inline-block">
                CALCULATE EARNINGS
              </a>
              <a href="#contact" className="btn-secondary inline-block">
                BECOME A PARTNER
              </a>
            </div>
          </div>
        </div>

        {/* Scroll Indicator */}
        <div className="absolute bottom-8 left-1/2 transform -translate-x-1/2 z-20">
          <div className="w-6 h-10 border-2 border-neon-blue rounded-full flex justify-center">
            <div className="w-1 h-3 bg-neon-blue rounded-full mt-2 animate-bounce" />
          </div>
        </div>

        {/* Fade transition */}
        <div className="absolute bottom-0 left-0 right-0 h-40 bg-gradient-to-b from-transparent to-[#0A0A0A] pointer-events-none" />
      </ParallaxHero>

      {/* Benefits Section */}
      <section className="py-20 px-4 relative">
        <div className="max-w-[1400px] mx-auto">
          <div className="text-center mb-16">
            <h2 className="text-4xl md:text-6xl font-tech font-black mb-4">
              <span className="text-white">WHY PARTNER WITH</span>{' '}
              <span className="neon-text">DT EXOTICS?</span>
            </h2>
            <p className="text-lg text-gray-400 max-w-3xl mx-auto">
              Professional fleet management that maximizes your vehicle's earning potential 
              while minimizing risk and hassle.
            </p>
          </div>

          <div className="grid md:grid-cols-2 xl:grid-cols-4 gap-8">
            {benefits.map((benefit, index) => (
              <div key={index} className="glass-panel bg-dark-metal/50 p-8 text-center group border border-gray-600/30 group-hover:border-neon-blue group-hover:shadow-[0_0_15px_rgba(0,255,255,0.3)] transition-all duration-700">
                <div className="w-24 h-24 mx-auto mb-6 rounded-full border-2 border-gray-600/30 group-hover:border-neon-blue flex items-center justify-center bg-dark-metal relative group-hover:scale-110 group-hover:shadow-[0_0_20px_rgba(0,255,255,0.4)] transition-all duration-700">
                  <div className="absolute inset-0 rounded-full bg-neon-blue/10 blur-xl group-hover:bg-neon-blue/30" />
                  <benefit.icon className="w-10 h-10 text-neon-blue relative z-10" />
                </div>
                
                <h3 className="text-lg font-tech font-bold mb-4 text-white">
                  {benefit.title}
                </h3>
                
                <p className="text-gray-300 text-sm leading-relaxed">
                  {benefit.description}
                </p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Revenue Calculator Section */}
      <section className="py-20 px-4 relative" id="calculator">
        <div className="max-w-[1000px] mx-auto">
          <div className="text-center mb-12">
            <h2 className="text-4xl md:text-6xl font-tech font-black mb-4">
              <span className="text-white">REVENUE</span>{' '}
              <span className="neon-text-magenta">CALCULATOR</span>
            </h2>
            <p className="text-lg text-gray-400 max-w-3xl mx-auto">
              See how much your luxury vehicle could earn with our 50/50 partnership model.
            </p>
          </div>

          <div className="glass-panel bg-dark-metal/50 p-8 border border-gray-600/30 rounded-2xl">
            <div className="grid md:grid-cols-2 gap-8">
              {/* Calculator Inputs */}
              <div>
                <h3 className="text-2xl font-tech font-bold text-white mb-6">Your Vehicle Details</h3>
                
                <div className="space-y-6">
                  <div>
                    <label className="block text-neon-blue font-tech font-semibold mb-2">
                      Vehicle Value
                    </label>
                    <input
                      type="range"
                      min="60000"
                      max="500000"
                      step="5000"
                      value={calculatorValues.vehicleValue}
                      onChange={(e) => {
                        const newVehicleValue = parseInt(e.target.value)
                        const newDailyRate = calculateDailyRate(newVehicleValue)
                        setCalculatorValues({
                          ...calculatorValues, 
                          vehicleValue: newVehicleValue,
                          dailyRate: newDailyRate
                        })
                      }}
                      className="w-full h-2 bg-gray-700 rounded-lg appearance-none cursor-pointer slider"
                    />
                    <div className="flex justify-between text-sm text-gray-400 mt-1">
                      <span>$60,000</span>
                      <span className="text-white font-tech">${calculatorValues.vehicleValue.toLocaleString()}</span>
                      <span>$500,000</span>
                    </div>
                  </div>

                  <div>
                    <label className="block text-neon-blue font-tech font-semibold mb-2">
                      Daily Rental Rate
                    </label>
                    <input
                      type="range"
                      min="200"
                      max="3000"
                      step="50"
                      value={calculatorValues.dailyRate}
                      onChange={(e) => setCalculatorValues({...calculatorValues, dailyRate: parseInt(e.target.value)})}
                      className="w-full h-2 bg-gray-700 rounded-lg appearance-none cursor-pointer slider"
                    />
                    <div className="flex justify-between text-sm text-gray-400 mt-1">
                      <span>$200</span>
                      <span className="text-white font-tech">${calculatorValues.dailyRate}/day</span>
                      <span>$3,000</span>
                    </div>
                  </div>

                  <div>
                    <label className="block text-neon-blue font-tech font-semibold mb-2">
                      Rental Days Per Month
                    </label>
                    <input
                      type="range"
                      min="5"
                      max="25"
                      step="1"
                      value={calculatorValues.monthlyDays}
                      onChange={(e) => setCalculatorValues({...calculatorValues, monthlyDays: parseInt(e.target.value)})}
                      className="w-full h-2 bg-gray-700 rounded-lg appearance-none cursor-pointer slider"
                    />
                    <div className="flex justify-between text-sm text-gray-400 mt-1">
                      <span>5 days</span>
                      <span className="text-white font-tech">{calculatorValues.monthlyDays} days</span>
                      <span>25 days</span>
                    </div>
                  </div>
                </div>
              </div>

              {/* Revenue Results */}
              <div>
                <h3 className="text-2xl font-tech font-bold text-white mb-6">Your Earnings</h3>
                
                <div className="space-y-6">
                  <div className="bg-dark-gray/50 p-6 rounded-lg border border-gray-600/30">
                    <div className="text-center">
                      <div className="text-sm text-gray-400 mb-1">Monthly Revenue</div>
                      <div className="text-2xl font-tech font-bold text-gray-300">
                        ${monthlyRevenue.toLocaleString()}
                      </div>
                    </div>
                  </div>

                  <div className="bg-neon-blue/10 p-6 rounded-lg border border-neon-blue/30">
                    <div className="text-center">
                      <div className="text-sm text-neon-blue mb-1">Your 50% Share</div>
                      <div className="text-3xl font-tech font-black text-neon-blue">
                        ${yourShare.toLocaleString()}/mo
                      </div>
                    </div>
                  </div>

                  <div className="bg-neon-pink/10 p-6 rounded-lg border border-neon-pink/30">
                    <div className="text-center">
                      <div className="text-sm text-neon-pink mb-1">Annual Income</div>
                      <div className="text-3xl font-tech font-black text-neon-pink">
                        ${annualRevenue.toLocaleString()}
                      </div>
                    </div>
                  </div>

                  <div className="text-center mt-6">
                    <a href="#contact" className="btn-primary inline-block">
                      START EARNING TODAY
                    </a>
                  </div>
                </div>
              </div>
            </div>

            <div className="mt-8 p-4 bg-gray-800/50 rounded-lg">
              <p className="text-xs text-gray-400 text-center">
                * Estimates based on market rates and historical data. Actual earnings may vary based on vehicle demand, 
                seasonality, and market conditions. DT Exotics handles all marketing, insurance, and operational costs.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* Turo vs DT Exotics Comparison */}
      <section className="py-20 px-4 relative">
        <div className="max-w-[1200px] mx-auto">
          <div className="text-center mb-16">
            <h2 className="text-4xl md:text-6xl font-tech font-black mb-4">
              <span className="neon-text">DT EXOTICS</span>{' '}
              <span className="text-white">VS TURO</span>
            </h2>
            <p className="text-lg text-gray-400 max-w-3xl mx-auto">
              See why luxury car owners choose professional fleet management over peer-to-peer platforms.
            </p>
          </div>

          <div className="grid md:grid-cols-2 gap-8">
            {/* DT Exotics Column */}
            <div className="glass-panel bg-dark-metal/50 p-8 border border-neon-blue/50 rounded-2xl">
              <div className="text-center mb-6">
                <h3 className="text-2xl font-tech font-bold text-neon-blue mb-2">DT EXOTICS PARTNERSHIP</h3>
                <div className="text-sm text-gray-400">Professional Vehicle Management</div>
              </div>

              <div className="space-y-4">
                <div className="flex items-start gap-3">
                  <CheckCircle className="w-5 h-5 text-neon-blue mt-1 flex-shrink-0" />
                  <div>
                    <div className="text-white font-semibold">50% Revenue Share</div>
                    <div className="text-gray-400 text-sm">Higher daily rates ($500-2000+)</div>
                  </div>
                </div>

                <div className="flex items-start gap-3">
                  <CheckCircle className="w-5 h-5 text-neon-blue mt-1 flex-shrink-0" />
                  <div>
                    <div className="text-white font-semibold">Commercial Insurance</div>
                    <div className="text-gray-400 text-sm">Full coverage, no gaps or exclusions</div>
                  </div>
                </div>

                <div className="flex items-start gap-3">
                  <CheckCircle className="w-5 h-5 text-neon-blue mt-1 flex-shrink-0" />
                  <div>
                    <div className="text-white font-semibold">Professional Screening</div>
                    <div className="text-gray-400 text-sm">Experienced luxury car renters only</div>
                  </div>
                </div>

                <div className="flex items-start gap-3">
                  <CheckCircle className="w-5 h-5 text-neon-blue mt-1 flex-shrink-0" />
                  <div>
                    <div className="text-white font-semibold">Secure Storage</div>
                    <div className="text-gray-400 text-sm">Climate-controlled facility</div>
                  </div>
                </div>

                <div className="flex items-start gap-3">
                  <CheckCircle className="w-5 h-5 text-neon-blue mt-1 flex-shrink-0" />
                  <div>
                    <div className="text-white font-semibold">Personal Insurance Safe</div>
                    <div className="text-gray-400 text-sm">No risk of cancellation</div>
                  </div>
                </div>

                <div className="flex items-start gap-3">
                  <CheckCircle className="w-5 h-5 text-neon-blue mt-1 flex-shrink-0" />
                  <div>
                    <div className="text-white font-semibold">Premium Market</div>
                    <div className="text-gray-400 text-sm">High-end clientele and events</div>
                  </div>
                </div>
              </div>
            </div>

            {/* Turo Column */}
            <div className="glass-panel bg-dark-metal/50 p-8 border border-gray-600/30 rounded-2xl">
              <div className="text-center mb-6">
                <h3 className="text-2xl font-tech font-bold text-gray-400 mb-2">TURO PLATFORM</h3>
                <div className="text-sm text-gray-400">Peer-to-Peer Car Sharing</div>
              </div>

              <div className="space-y-4">
                <div className="flex items-start gap-3">
                  <div className="w-5 h-5 border-2 border-red-500 rounded-full mt-1 flex-shrink-0 flex items-center justify-center">
                    <div className="w-3 h-0.5 bg-red-500"></div>
                  </div>
                  <div>
                    <div className="text-gray-300 font-semibold">60-75% After Fees</div>
                    <div className="text-gray-500 text-sm">Lower rates, high platform fees</div>
                  </div>
                </div>

                <div className="flex items-start gap-3">
                  <div className="w-5 h-5 border-2 border-red-500 rounded-full mt-1 flex-shrink-0 flex items-center justify-center">
                    <div className="w-3 h-0.5 bg-red-500"></div>
                  </div>
                  <div>
                    <div className="text-gray-300 font-semibold">Secondary Coverage</div>
                    <div className="text-gray-500 text-sm">Insurance gaps, high deductibles</div>
                  </div>
                </div>

                <div className="flex items-start gap-3">
                  <div className="w-5 h-5 border-2 border-red-500 rounded-full mt-1 flex-shrink-0 flex items-center justify-center">
                    <div className="w-3 h-0.5 bg-red-500"></div>
                  </div>
                  <div>
                    <div className="text-gray-300 font-semibold">Anyone Can Rent</div>
                    <div className="text-gray-500 text-sm">Inexperienced drivers, potential abuse</div>
                  </div>
                </div>

                <div className="flex items-start gap-3">
                  <div className="w-5 h-5 border-2 border-red-500 rounded-full mt-1 flex-shrink-0 flex items-center justify-center">
                    <div className="w-3 h-0.5 bg-red-500"></div>
                  </div>
                  <div>
                    <div className="text-gray-300 font-semibold">Public Exposure</div>
                    <div className="text-gray-500 text-sm">Home address known, security risk</div>
                  </div>
                </div>

                <div className="flex items-start gap-3">
                  <div className="w-5 h-5 border-2 border-red-500 rounded-full mt-1 flex-shrink-0 flex items-center justify-center">
                    <div className="w-3 h-0.5 bg-red-500"></div>
                  </div>
                  <div>
                    <div className="text-gray-300 font-semibold">Insurance Risk</div>
                    <div className="text-gray-500 text-sm">Personal policy cancellation risk</div>
                  </div>
                </div>

                <div className="flex items-start gap-3">
                  <div className="w-5 h-5 border-2 border-red-500 rounded-full mt-1 flex-shrink-0 flex items-center justify-center">
                    <div className="w-3 h-0.5 bg-red-500"></div>
                  </div>
                  <div>
                    <div className="text-gray-300 font-semibold">General Market</div>
                    <div className="text-gray-500 text-sm">Price-sensitive, casual renters</div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Process Steps Section */}
      <section className="py-20 px-4 relative">
        <div className="max-w-[1400px] mx-auto">
          <div className="text-center mb-16">
            <h2 className="text-4xl md:text-6xl font-tech font-black mb-4">
              <span className="text-white">SIMPLE</span>{' '}
              <span className="neon-text-magenta">PROCESS</span>
            </h2>
            <p className="text-lg text-gray-400 max-w-3xl mx-auto">
              Getting started with our partnership program is straightforward and hassle-free.
            </p>
          </div>

          <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-8">
            {steps.map((step, index) => (
              <div key={index} className="text-center group">
                <div className="w-24 h-24 mx-auto mb-6 rounded-full border-2 border-gray-600/30 group-hover:border-neon-pink flex items-center justify-center bg-dark-metal relative group-hover:scale-110 group-hover:shadow-[0_0_20px_rgba(255,0,255,0.4)] transition-all duration-700">
                  <div className="absolute inset-0 rounded-full bg-neon-pink/10 blur-xl group-hover:bg-neon-pink/30" />
                  <step.icon className="w-10 h-10 text-neon-pink relative z-10" />
                </div>
                
                <h3 className="text-xl font-tech font-bold mb-4 text-white">
                  <span className="text-neon-pink font-tech font-black">{step.number}.</span> {step.title}
                </h3>
                
                <p className="text-gray-300 text-sm leading-relaxed">
                  {step.description}
                </p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Vehicle Requirements Section */}
      <section className="py-20 px-4 relative">
        <div className="max-w-[1000px] mx-auto">
          <div className="text-center mb-12">
            <h2 className="text-4xl md:text-6xl font-tech font-black mb-4">
              <span className="text-white">VEHICLE</span>{' '}
              <span className="neon-text">REQUIREMENTS</span>
            </h2>
            <p className="text-lg text-gray-400 max-w-3xl mx-auto">
              We accept high-end vehicles that meet our luxury standards and market demand.
            </p>
          </div>

          <div className="grid md:grid-cols-2 gap-8">
            <div className="glass-panel bg-dark-metal/50 p-8 border border-gray-600/30 rounded-2xl">
              <h3 className="text-xl font-tech font-bold text-white mb-6">Qualifying Brands</h3>
              <div className="grid grid-cols-2 gap-4 text-gray-300">
                <div className="flex items-center gap-2">
                  <Car className="w-4 h-4 text-neon-blue" />
                  <span>Audi R8/S/RS</span>
                </div>
                <div className="flex items-center gap-2">
                  <Car className="w-4 h-4 text-neon-blue" />
                  <span>Bentley</span>
                </div>
                <div className="flex items-center gap-2">
                  <Car className="w-4 h-4 text-neon-blue" />
                  <span>BMW i8/M Series</span>
                </div>
                <div className="flex items-center gap-2">
                  <Car className="w-4 h-4 text-neon-blue" />
                  <span>Bugatti</span>
                </div>
                <div className="flex items-center gap-2">
                  <Car className="w-4 h-4 text-neon-blue" />
                  <span>Corvette ZR-1/C8</span>
                </div>
                <div className="flex items-center gap-2">
                  <Car className="w-4 h-4 text-neon-blue" />
                  <span>Ferrari</span>
                </div>
                <div className="flex items-center gap-2">
                  <Car className="w-4 h-4 text-neon-blue" />
                  <span>Koenigsegg</span>
                </div>
                <div className="flex items-center gap-2">
                  <Car className="w-4 h-4 text-neon-blue" />
                  <span>Lamborghini</span>
                </div>
                <div className="flex items-center gap-2">
                  <Car className="w-4 h-4 text-neon-blue" />
                  <span>Lotus</span>
                </div>
                <div className="flex items-center gap-2">
                  <Car className="w-4 h-4 text-neon-blue" />
                  <span>Maserati</span>
                </div>
                <div className="flex items-center gap-2">
                  <Car className="w-4 h-4 text-neon-blue" />
                  <span>McLaren</span>
                </div>
                <div className="flex items-center gap-2">
                  <Car className="w-4 h-4 text-neon-blue" />
                  <span>Mercedes AMG</span>
                </div>
                <div className="flex items-center gap-2">
                  <Car className="w-4 h-4 text-neon-blue" />
                  <span>Porsche</span>
                </div>
                <div className="flex items-center gap-2">
                  <Car className="w-4 h-4 text-neon-blue" />
                  <span>Rolls Royce</span>
                </div>
              </div>
            </div>

            <div className="glass-panel bg-dark-metal/50 p-8 border border-gray-600/30 rounded-2xl">
              <h3 className="text-xl font-tech font-bold text-white mb-6">Requirements</h3>
              <div className="space-y-4">
                <div className="flex items-start gap-3">
                  <CheckCircle className="w-5 h-5 text-neon-blue mt-1 flex-shrink-0" />
                  <div>
                    <div className="text-white font-semibold">$60,000+ Value</div>
                    <div className="text-gray-400 text-sm">Current market value minimum</div>
                  </div>
                </div>
                <div className="flex items-start gap-3">
                  <CheckCircle className="w-5 h-5 text-neon-blue mt-1 flex-shrink-0" />
                  <div>
                    <div className="text-white font-semibold">7 Years or Newer</div>
                    <div className="text-gray-400 text-sm">Model year requirements</div>
                  </div>
                </div>
                <div className="flex items-start gap-3">
                  <CheckCircle className="w-5 h-5 text-neon-blue mt-1 flex-shrink-0" />
                  <div>
                    <div className="text-white font-semibold">Clean Title</div>
                    <div className="text-gray-400 text-sm">No salvage or flood history</div>
                  </div>
                </div>
                <div className="flex items-start gap-3">
                  <CheckCircle className="w-5 h-5 text-neon-blue mt-1 flex-shrink-0" />
                  <div>
                    <div className="text-white font-semibold">Excellent Condition</div>
                    <div className="text-gray-400 text-sm">Well-maintained inside and out</div>
                  </div>
                </div>
                <div className="flex items-start gap-3">
                  <CheckCircle className="w-5 h-5 text-neon-blue mt-1 flex-shrink-0" />
                  <div>
                    <div className="text-white font-semibold">Current Registration</div>
                    <div className="text-gray-400 text-sm">Valid Nevada registration preferred</div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* FAQ Section */}
      <section className="py-20 px-4 relative">
        <div className="max-w-[1000px] mx-auto">
          <div className="text-center mb-12">
            <h2 className="text-4xl md:text-6xl font-tech font-black mb-4">
              <span className="text-white">PARTNERSHIP</span>{' '}
              <span className="neon-text">FAQ</span>
            </h2>
            <p className="text-lg text-gray-400 max-w-3xl mx-auto">
              Common questions about joining our vehicle partnership program.
            </p>
          </div>

          <div className="space-y-4">
            {faqs.map((faq) => (
              <FAQAccordion
                key={faq.id}
                id={faq.id}
                question={faq.question}
                answer={faq.answer}
                isOpen={openFAQ === faq.id}
                onToggle={toggleFAQ}
                faqRef={(el) => { faqRefs.current[faq.id] = el }}
              />
            ))}
          </div>
        </div>
      </section>

      {/* Contact Form Section */}
      <EventContactForm
        eventType="partners"
        title="JOIN OUR PARTNERSHIP PROGRAM"
        subtitle="Turn your exotic vehicle into a profitable asset with Las Vegas's premier luxury car rental fleet. Tell us about your vehicle and we'll provide a custom earning analysis."
        fields={getFormFields('partners')}
        submitButtonText="APPLY FOR PARTNERSHIP"
        successMessage="Thank you for your interest in our partnership program! Our fleet management team will review your vehicle information and contact you within 48 hours with a detailed earning analysis and next steps to join our exclusive network."
      />

      <Footer />
    </main>
  )
}